plugin:
    name: 'mavitm.estate::lang.plugin.name'
    description: 'mavitm.estate::lang.plugin.description'
    author: MaviTm
    icon: oc-icon-building
    homepage: ''
permissions:
    mavitm.estate.access.realty:
        tab: 'mavitm.estate::lang.plugin.name'
        label: 'mavitm.estate::lang.plugin.name'
navigation:
    estate:
        label: 'mavitm.estate::lang.plugin.name'
        url: mavitm/estate/realties
        icon: icon-building
        permissions:
            - mavitm.estate.access.realty
        sideMenu:
            realty:
                label: 'mavitm.estate::lang.plugin.name'
                url: mavitm/estate/realties
                icon: icon-building-o
                permissions:
                    - mavitm.estate.access.realty
            category:
                label: 'mavitm.estate::lang.plugin.category'
                url: mavitm/estate/categories
                icon: icon-folder
                permissions:
                    - mavitm.estate.access.realty
            tags:
                label: 'mavitm.estate::lang.tags.title'
                url: mavitm/estate/tags
                icon: icon-tags
                permissions:
                    - mavitm.estate.access.realty
